### ISSUE TITLE
MacOS Flash error

### ISSUE THREAD

**Issue by mkintzel** [EdgeTX/flasher#19]
Trying to Flash a RadioMaster TX16s from a MacBook macOS BigSur.  I have flashed this radio previously with OpenTX from OpenTX companion.  I have not tried that method for EdgeTX as was hoping to use your new utilities.  I receive the following message immediately upon pressing the "Flash Radio Firmware" button.  (By the way, this differs slightly from the Installation Guide which mentions selecting "Write")  Thank you for all your work on this project!!
<img width="590" alt="image" src="https://user-images.githubusercontent.com/80914443/128548072-1cb53f18-ff3f-4889-94a2-a937b94169f4.png">

**Comment by artem-alexandrov** [comment]
+1 having the same issue

**Comment by richard-scott** [comment]
Have you tried this?

```
brew install dfu-util
```

**Comment by mkintzel** [comment]
Thank you @richard-scott  that solved my problem!!  Now to get a model setup and back to flying!  Love the new Edge interface!

**Comment by CoderElectronics** [comment]
> Have you tried this?
> 
> ```
> brew install dfu-util
> ```

That's the perfect solution for now, i'm compiling new dfu-util binaries as we speak that should fix that

**Comment by lerni** [comment]
On OSX (as originally reported) installing dfu-util per brew is still needed with latest (#16fb26b3562e653abe9d09c6ecc843a257d79c7b) as of 20th of april 22
