### ISSUE TITLE
SD card setup doesn't complete when there is no sound pack selected

### ISSUE THREAD

**Issue by Nine-H** [EdgeTX/flasher#21]
I did two attempts for my x7, one for two hours, one for 40 minutes and neither completed in the flasher window, but the card seemed to have all the necessary files. I took a brief look at SDCardPage.vue and it appears that the case where no sound packs are selected is not actually handled, hence the interface hang. It'd be nice to skip the download of the archive manifest thing when nothing is selected as well.

I understand the purpose of talking radios, I just find them a little cringe and figure I can save the SD card space.

**Comment by CoderElectronics** [comment]
This should be fixed in the latest release, please re-open if you have any issues.
