### ISSUE TITLE
Incompatible version of dfu util deliverd with win releas.  

### ISSUE THREAD

**Issue by fear** [EdgeTX/flasher#28]
The actual release delivers the dfu-util v0.10 binaries wich seems to be broken. After downgrading to dfu-util 0.9 in the installationfolder everything is working fine. 

![2021-09-01 09_42_45-edgetx-flasher](https://user-images.githubusercontent.com/2143245/131632375-3a2a762a-265d-40db-ae58-280276d3c0da.png)

May there is an option to build the win version with the working dfu-util until 11 is released which hopefully fixes the problem

**Comment by CoderElectronics** [comment]
This is all fixed in #fc69302.

All DFU binaries have been updated to v0.11

**Comment by fear** [comment]
Nice, everything working again :)
