### ISSUE TITLE
Version still not being shown on Windows builds

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/flasher#35]
As has been pointed out a few times now, and was also the reason for https://github.com/EdgeTX/flasher/pull/27, version numbers are still not being shown on Windows builds. Visible here, also on the screenshot Risto posted in Discord when talking about the wizard. 

![image](https://user-images.githubusercontent.com/5500713/143333325-04eba2b9-5a6b-4de8-b992-640176ab972f.png)

**Comment by CoderElectronics** [comment]
Let me look at this

**Comment by Prasanna-icefire** [comment]
Same issue.....I tried checking the linux deb app, the issue persists...

**Comment by pfeerick** [comment]
With the latest release? I do get it on Windows now. 

![image](https://user-images.githubusercontent.com/5500713/155829061-9dee01f1-3ae8-49df-a061-02938c27e43f.png)

**Comment by Prasanna-icefire** [comment]
![IssueEdgeTX](https://user-images.githubusercontent.com/46682369/155829885-d1a63da9-f1a9-4715-8f24-ec1883439128.png)

This is the issue faced....

**Comment by pfeerick** [comment]
Ah, ok, that is different problem to the one this issue was in relation to - it was only no version number was being shown on the windows builds (which is resolved now, as the github hash is being shown now - although that still needs improving on), not that no downloads were available. I'm seeing that also now that I try here. This could be a github issue, or an issue with flasher, not sure yet.

**Comment by richard-scott** [comment]
I get this on Ubuntu too ;-(

**Comment by CoderElectronics** [comment]
This is all fixed, closing now, if you are still missing it update to the latest GH release and it should be there, please reopen if this is incorrect.
