### ISSUE TITLE
Horus X10 flash goes fail with wrong PCB detected 

### ISSUE THREAD

**Issue by Skippydi** [EdgeTX/flasher#36]
Today I tried again to flash the transmitter, just like yesterday with Horus x10 main.(2012-11-26-10:53:38
What can I tell you, now wrong PCB detected comes back. Yesterday was it fine.

**Comment by CoderElectronics** [comment]
All fixed in https://github.com/EdgeTX/flasher/commit/2ecfcb443744e51c2c557980db783f51c225d690

**Comment by Skippydi** [comment]
Thx

Ari Stehney ***@***.***> schrieb am Fr. 26. Nov. 2021 um
19:58:
