### ISSUE TITLE
SD Card pack incorrectly being unzipped

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/flasher#4]
When I selected the TX16S as the target radio, it seems like the complete wrong version of the SD card pack was downloaded. It's not the zip file, but the wrong version - i.e.  background graphic is the opentx one, not the edgetx one and there are scripts which were removed from the pack a week or so ago). I double checked against the latest rolling release of the sdcard repo just to check I wasn't going crazy! 😆 

Also just noticed `edgetx.sdcard.version` is completely missing... I was waiting for the nightly build of ETX to go though before testing, so am finally testing both the flasher and the sdcard pack stuff. 

Flashing worked perfectly for the nightly, btw. Nice to see the commit hashes and that any testing/wip branches also automatically pop up ;)

**Comment by CoderElectronics** [comment]
Ok so we need to diff and merge in changes from RC1, it is still functional but there are changes that for some reason are in RC1 instead of in the latest repo through a PR. Let's see if we can get all those into the master branch of the SD Card repo.

**Comment by pfeerick** [comment]
No, not quite - it _seems_ like there is a recursion problem when the files are written to the SD card. 

More here:
https://discord.com/channels/839849772864503828/839865370440630302/857779432454225961

**Comment by CoderElectronics** [comment]
I believe your PR fixed the issue, thank you!
