### ISSUE TITLE
[Feature Request] linux support - deb or tar.gz

### ISSUE THREAD

**Issue by nightflasher** [EdgeTX/flasher#40]
i am on ubuntu and would like to see some linux program in deb or tar.gz format.

**Comment by CoderElectronics** [comment]
The AppImage format would work for most Linux systems including Ubuntu, But I will add support for Deb in the next few days as I could see it being helpful.

**Comment by nightflasher** [comment]
Deb is much lighter and works better with the system libraries. AppImages doesn't always work.
