### ISSUE TITLE
SDCard Tab buttons are disabled

### ISSUE THREAD

**Issue by MartinHugh** [EdgeTX/flasher#41]
[Running on Chrome Version 98.0.4758.102 (Official Build) (64-bit)]

I am having some problems applying SD content from the Buddy tool

When I select "SD Card Content tab" , 
Firmware Version : "EdgeTX "Santa" v2.6.0SD Card Pack"
RadioModel : TX16S

None of the buttons (Revert Apply, Reinstall) are enabled.

What am I missing ?

**Comment by CoderElectronics** [comment]
Could you please send me a screenshot of the error? I would suggest moving this issue over to the edgetx buddy issues tab.
