### ISSUE TITLE
Problem with "Setup SD Card"

### ISSUE THREAD

**Issue by sergiobellini** [EdgeTX/flasher#45]
Hi,
when click on "Setup SD Card" no Voicepack and no Lua scripts are shown, and no Disk into selectbox.

In loggin:
[updateConfig.message.error][2022-06-08T13:30:40.338Z] Error: Request failed with status code 404

Thanks

PS: both Windows & MacOS version

**Comment by munzli** [comment]
same problem. 
tried linux deb and appimage

**Comment by Potatotatotato** [comment]
Me,too

**Comment by jawz101** [comment]
On Windows I get an error in the event log

```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{2593F8B9-4EAF-457C-B68A-50F6B8EA6B54}
 and APPID 
{15C20B67-12E7-4BB6-92BB-7AFF07997402}
 to the user computername\username SID (S-1-5-21-2752922228-1345440906-3538473472-1001) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```

**Comment by xxz3** [comment]
+1 on MacOS Big Sur 11.6.5 - edgetx flasher 16fb26b

**Comment by brunohenriquy** [comment]
Same here, MacOS and Windows 11.

**Comment by brunohenriquy** [comment]
https://docs.microsoft.com/en-us/answers/questions/281617/the-application-specific-permission-settings-do-no-1.html
Tried this, but don't work!
