### ISSUE TITLE
[SDCARD] Check for a valid target before showing erasure warning...

### ISSUE THREAD

**Issue by pfeerick** [EdgeTX/flasher#5]
... as if you haven't picked a valid target, you're not going to be erasing anything...

i.e. current behaviour: 
![J4Z9Kw3vTW](https://user-images.githubusercontent.com/5500713/123355366-e0f05180-d5a8-11eb-8b57-2be248326d2b.gif)

**Comment by pfeerick** [comment]
Also, it would probably be a good idea to prompt to user to take the transmitter out of DFU mode if they have just updated the firmware.

**Comment by pfeerick** [comment]
i.e. "Please select a valid disk, and ensure your transmitter is not in DFU mode"

**Comment by CoderElectronics** [comment]
Should be all fixed, please take a look

**Comment by CoderElectronics** [comment]
The dialog display order is fixed here: https://github.com/EdgeTX/flasher/commit/8d5b14a8e7e8186dbe9344dfc4ca2015740cfd6c
